wandb_version: 1

batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.001
dataset:
  desc: null
  value: ./spa-eng/spa.txt
epochs:
  desc: null
  value: 25
latent_dim:
  desc: null
  value: 256
cell_type:
  desc: null
  value: GRU
optimizer:
  desc: null
  value: RMSprop
lstm_layers:
  desc: null
  value: 2
dropouts:
  desc: null
  value: 0.4
_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716901623
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.5
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
