wandb_version: 1

batch_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.0001
dataset:
  desc: null
  value: ./spa-eng/spa.txt
epochs:
  desc: null
  value: 2
latent_dim:
  desc: null
  value: 256
cell_type:
  desc: null
  value: LSTM
optimizer:
  desc: null
  value: RMSprop
lstm_layers:
  desc: null
  value: 1
dropouts:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716363068
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.2
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
